import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth, hashPassword, validatePasswordStrength, generateRandomPassword } from "@/lib/auth";
import { generateAdminUsername } from "@/lib/admin-username";
import { ok, created, forbidden, notFound, error, serverError } from "@/lib/api-response";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = requireAuth(req);
  if (!session || session.role !== "super_admin") return forbidden();

  const { id: clinicId } = await params;

  const clinic = await prisma.clinic.findUnique({ where: { id: clinicId } });
  if (!clinic) return notFound("Klinika topilmadi");

  const admins = await prisma.user.findMany({
    where: { clinicId, role: "clinic_admin" },
    select: {
      id: true,
      username: true,
      firstName: true,
      lastName: true,
      phone: true,
      isActive: true,
      createdAt: true,
    },
    orderBy: { createdAt: "desc" },
  });

  return ok({ admins, total: admins.length });
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = requireAuth(req);
  if (!session || session.role !== "super_admin") return forbidden();

  const { id: clinicId } = await params;

  const clinic = await prisma.clinic.findUnique({ where: { id: clinicId } });
  if (!clinic) return notFound("Klinika topilmadi");

  try {
    const body = await req.json();
    const { firstName, lastName, phone, password, autoPassword } = body;

    if (!firstName || typeof firstName !== "string" || firstName.trim().length < 2) {
      return error("Ism kamida 2 belgi bo'lishi kerak");
    }

    let finalPassword: string;
    if (autoPassword) {
      finalPassword = generateRandomPassword(12);
    } else {
      if (!password || typeof password !== "string") return error("Parol kerak");
      const check = validatePasswordStrength(password);
      if (!check.valid) return error(check.error!);
      finalPassword = password;
    }

    if (phone) {
      const existing = await prisma.user.findUnique({ where: { phone } });
      if (existing) return error("Bu telefon raqami allaqachon ro'yxatdan o'tgan", 409);
    }

    const username = await generateAdminUsername();
    const passwordHash = await hashPassword(finalPassword);

    const newAdmin = await prisma.user.create({
      data: {
        clinicId,
        username,
        firstName: firstName.trim(),
        lastName: lastName?.trim() || null,
        phone: phone || null,
        passwordHash,
        role: "clinic_admin",
        isActive: true,
      },
      select: {
        id: true,
        username: true,
        firstName: true,
        lastName: true,
        phone: true,
        isActive: true,
        createdAt: true,
      },
    });

    await prisma.auditLog.create({
      data: {
        actorId: session.userId,
        clinicId,
        action: "admin.create",
        payload: {
          adminId: newAdmin.id,
          username: newAdmin.username,
          autoGeneratedPassword: !!autoPassword,
        },
      },
    });

    return created({
      admin: newAdmin,
      credentials: { username, password: finalPassword },
    });
  } catch {
    return serverError();
  }
}
