import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth, hashPassword, validatePasswordStrength, generateRandomPassword } from "@/lib/auth";
import { sessionUser, canCreateBranchAdmin, canManageBranch } from "@/lib/permissions";
import { generateBranchAdminUsername } from "@/lib/admin-username";
import { ok, created, forbidden, notFound, error, unauthorized, serverError } from "@/lib/api-response";

type RouteParams = { params: Promise<{ id: string; branchId: string }> };

export async function GET(req: NextRequest, { params }: RouteParams) {
  const jwt = requireAuth(req);
  if (!jwt) return unauthorized();

  const { id: clinicId, branchId } = await params;
  const user = sessionUser(jwt);

  if (!canManageBranch(user, clinicId, branchId)) return forbidden();

  const branch = await prisma.branch.findFirst({
    where: { id: branchId, clinicId },
  });
  if (!branch) return notFound("Filial topilmadi");

  const admins = await prisma.user.findMany({
    where: { branchId, role: "branch_admin" },
    select: {
      id: true,
      username: true,
      firstName: true,
      lastName: true,
      phone: true,
      isActive: true,
      createdAt: true,
    },
    orderBy: { createdAt: "desc" },
  });

  return ok({ admins, total: admins.length });
}

export async function POST(req: NextRequest, { params }: RouteParams) {
  const jwt = requireAuth(req);
  if (!jwt) return unauthorized();

  const { id: clinicId, branchId } = await params;
  const user = sessionUser(jwt);

  if (!canCreateBranchAdmin(user, clinicId)) return forbidden("Filialga admin yaratish ruxsati yo'q");

  const branch = await prisma.branch.findFirst({
    where: { id: branchId, clinicId, isActive: true },
  });
  if (!branch) return notFound("Filial topilmadi yoki nofaol");

  try {
    const body = await req.json();
    const { firstName, lastName, phone, password, autoPassword } = body;

    if (!firstName || typeof firstName !== "string" || firstName.trim().length < 2) {
      return error("Ism kamida 2 belgi bo'lishi kerak");
    }

    if (phone) {
      const cleaned = (phone as string).replace(/\D/g, "");
      if (cleaned.length < 9 || cleaned.length > 12) {
        return error("Telefon noto'g'ri");
      }
      const existing = await prisma.user.findUnique({ where: { phone } });
      if (existing) return error("Bu telefon raqam allaqachon band", 409);
    }

    let finalPassword: string;
    if (autoPassword) {
      finalPassword = generateRandomPassword(12);
    } else {
      if (!password) return error("Parol kerak");
      const check = validatePasswordStrength(password);
      if (!check.valid) return error(check.error!);
      finalPassword = password;
    }

    const username = await generateBranchAdminUsername();
    const passwordHash = await hashPassword(finalPassword);

    const newAdmin = await prisma.user.create({
      data: {
        clinicId,
        branchId,
        username,
        firstName: firstName.trim(),
        lastName: lastName?.trim() || null,
        phone: phone || null,
        passwordHash,
        role: "branch_admin",
        isActive: true,
      },
      select: {
        id: true,
        username: true,
        firstName: true,
        lastName: true,
        phone: true,
        isActive: true,
        createdAt: true,
      },
    });

    await prisma.auditLog.create({
      data: {
        actorId: user.id,
        clinicId,
        action: "branch_admin.create",
        payload: {
          adminId: newAdmin.id,
          branchId,
          username: newAdmin.username,
          autoGeneratedPassword: !!autoPassword,
        },
      },
    });

    return created({ admin: newAdmin, credentials: { username, password: finalPassword } });
  } catch {
    return serverError();
  }
}
